# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4e4dc1c46cf6ca34d651a4868eeace47d18f9e15357fec13808c0addcd176ad3dd1512359c41ea7dc5f75aacce2a949411019aeeac86533a2932e0c0333bceaf

test:
  secret_key_base: 458e4011e1855e12019e684fb6eb45ef0f6db7643f88c4f278487db0b8527b499b610666cfaead91f51a932205f0b975c69f9d284ec29ce0994479d8b6c56a76

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
